### ISSUE TITLE
Fix eslint configuration

### ISSUE THREAD

**Issue by probil** [liubich/react-mem-game#13]
Currently your eslint/style configuration is following:
```
    "lint:js": "eslint src/*.js",
    "lint:css": "stylelint src/*.css",
```
It it works well when your code is in `src` directory. But after component splitting it will not work because `src/*.js` cover only js files in src without subdirectories.
To make it scan subdirectories we need another glob expression - `src/**/*.js`

Update your configuration please

**Comment by liubich** [comment]
Closed at [#16](https://github.com/liubich/react-mem-game/pull/16)
