### ISSUE TITLE
Replace card icons

### ISSUE THREAD

**Issue by probil** [liubich/react-mem-game#23]
Currently some icons are colored and some are just black. I don't like it. Plus framework logos are not interesting
Let's use one icon set for all the cards.

I've found free icon set here https://roundicons.com/icon-packs/free-flat-icons-vol-2-icons/ (just type your email and download 100 icons in svg)

You can use them or pick your own icon set

**Comment by liubich** [comment]
@probil, copy this issue into vanilla JS project, please.
